football_action = {
    "skill": ["long pass",
              "short pass",
              "flank pass",
              "high lobbing pass",
              "scissor pass",
              "volley pass",
              "hook pass",
              "triangular pass",
              "rolling pass",
              "back pass",
              "steep forward pass",
              "cross",
              "send in a cross",
              "line pass",
              "back-heel pass",
              "flick-on header",
              "back pass",
              "overhead kick",
              "chest-high ball",
              "ground ballr",
              "ball handling",
              "block tackle",
              "interception",
              "body check",
              "fair charge",
              "chesting",
              "close defence",
              "consecutive passes",
              "diving header",
              "flying headar",
              "dribbling",
              "beat an opponent",
              "slide tackle",
              "steal a ball",
              "bullt",
              "clearance kick",
              "powerful kick",
              "goalkeeping",
              "clean catching",
              "beat out a shot",
              "to shoot",
              "rebound",
              "banana shot",
              "volley shot",
              "grazing shot",
              "close-range shot",
              "long drive",
              "mishit",
              "free shot",
              "tap in the ball",
              "open net",
              "solo drive",
              "wall pass",
              "to pass the ball",
              "runing off the ball",
              "support",
              "to take a pass",
              "trapping",
              "spot pass",
              "make a spot pass",
              "to trap",
              "to intercept",
              "to break through",
              "to break loose",
              "break through",
              "thrust",
              "empty space",
              "make space",
              "blanket defence",
              "man to man defence",
              "mark space",
              "offensive on wings",
              "aerial duel",
              "fast break",
              "fast counterattack",
              "beat offside trap",
              "drop-ball",
              "control midfield",
              "disorganize defence",
              "to fall back",
              "to set pace",
              "tempo of game",
              "ward off assault",
              "break up attack"],

    "fight": ["all-out attacking",
              "total football",
              "open football",
              "off-side trap",
              "wing play",
              "time wasting"]
}
